### DISCUSSION TITLE
install/commercial/cluster-config/

### DISCUSSION THREAD

**Discussion by giscus** [DaoCloud/DaoCloud-docs#1200] [Announcements]
# install/commercial/cluster-config/

DaoCloud Enterprise 5.0 下一代容器化平台集大成者，引领云原生浪潮，推动数字化转型。

https://docs.daocloud.io/install/commercial/cluster-config/

**Comment by leolingg** [comment]
```yaml
binaries: # 二进制可执行文件

    # official-service(default), builtin
    type: builtin

```
配置样板binaries字段顶格，应该在spec下面
