### DISCUSSION TITLE
amamba/quickstart/scenarios-config

### DISCUSSION THREAD

**Discussion by giscus** [DaoCloud/DaoCloud-docs#2553] [Announcements]
# amamba/quickstart/scenarios-config

DaoCloud Enterprise 5.0 下一代容器化平台集大成者，引领云原生浪潮，推动数字化转型。

https://docs.daocloud.io/amamba/quickstart/scenarios-config.html?h=

**Comment by muma378** [comment]
补充下 如何修改worker并发数：

部署的时候：
```yaml
  Casc:
    # Maximum number of parallel pipelines
    maxParallelRuns:  2
```

部署之后在：

jenkins-casc-config
 jenkins.yaml
 containerCapStr 

设置
