### DISCUSSION TITLE
storage/hwameistor/resources/lvm-nodes/

### DISCUSSION THREAD

**Discussion by giscus** [DaoCloud/DaoCloud-docs#5226] [Announcements]
# storage/hwameistor/resources/lvm-nodes/

DaoCloud Enterprise 5.0 下一代容器化平台集大成者，引领云原生浪潮，推动数字化转型。

https://docs.daocloud.io/storage/hwameistor/resources/lvm-nodes/

**Comment by peterchenhc** [comment]
添加新增存储节点到 HwameiStor 系统
加入  description: 无法正常纳管磁盘

```
kubectl apply -f - <<EOF
apiVersion: hwameistor.io/v1alpha1
kind: LocalDiskClaim
metadata:
  name: szldce5wr10vd
spec:
  nodeName: szldce5wr10vd
  owner: local-storage
EOF
```
