### ISSUE TITLE
[可观测性]通过Operator实现应用程序无侵入增强-python应用采集链路失败

### ISSUE THREAD

**Issue by tukwila** [DaoCloud/DaoCloud-docs#2790]
测试环境：
worker集群：root@10.6.127.22密码root
python demo deployment yaml文件：
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-py-app
  labels:
    app: my-py-app
spec:
  selector:
    matchLabels:
      app: my-py-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-py-app
      annotations:
        instrumentation.opentelemetry.io/inject-python: "insight-system/insight-opentelemetry-autoinstrumentation"
    spec:
      containers:
      - name: mypyapp
        image: release-ci.daocloud.io/insight-ci/py-demo@sha256:0716ebc5228d6a390dc0b0bdff11a184d5c5a25def9699801822d780adea3bf4 
        ports:
          - containerPort: 8080
            protocol: TCP
```
