### ISSUE TITLE
【submariner 使用说明】手动配置 Calico 的 IPPool 时，描述有误。

### ISSUE THREAD

**Issue by ty-dc** [DaoCloud/DaoCloud-docs#2870]
https://docs.daocloud.io/network/modules/submariner/usage.html

如下图片中，描述有误
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/101157744/e7cfff00-c2a3-42c7-95c1-09dd49115e50)

正确的应该是

在 Cluster B 执行同样操作：
```
cat > clusterb-cidr.yaml <<EOF
  apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    name: clusterA-pod-cidr
  spec:
    cidr: 10.244.64.0/18
    natOutgoing: false
    disabled: true
EOF

cat > podwestcluster.yaml <<EOF
  apiVersion: projectcalico.org/v3
  kind: IPPool
  metadata:
    name: clusterA-service-cidr
  spec:
    cidr: 10.244.0.0/18
    natOutgoing: false
    disabled: true
EOF
```
