### ISSUE TITLE
【hwameistor】"添加新增存储节点到 HwameiStor 系统" yaml文件需要更新

### ISSUE THREAD

**Issue by FloatXD** [DaoCloud/DaoCloud-docs#3092]
https://docs.daocloud.io/storage/hwameistor/resources/lvm-nodes/#1
![图片](https://github.com/DaoCloud/DaoCloud-docs/assets/76234281/acad8546-303c-4b25-a2d6-a8ea066129ea)
应为：
```
apiVersion: hwameistor.io/v1alpha1
kind: LocalDiskClaim
metadata:
  name: k8s-worker-4
spec:
  nodeName: k8s-worker-4
  owner: local-storage
  description:
    diskType: SSD
EOF
```
