### ISSUE TITLE
 【hwameistor】“数据卷迁移”创建迁移任务yaml文件错误

### ISSUE THREAD

**Issue by FloatXD** [DaoCloud/DaoCloud-docs#3098]
https://docs.daocloud.io/storage/hwameistor/resources/migrate/#_5
![图片](https://github.com/DaoCloud/DaoCloud-docs/assets/76234281/19fd6732-4e3c-4940-ac97-e28fb78a720f)
应为：
```
apiVersion: hwameistor.io/v1alpha1
kind: LocalVolumeMigrate
metadata:
  namespace: hwameistor
  name: <localVolumeMigrateName>
spec:
  sourceNode: <sourceNodeName>
  targetNodesSuggested: 
  - <targetNodesName1>
  - <targetNodesName2>
  volumeName: <volName>
  migrateAllVols: <true/false>
```

**Comment by Fan-Lin** [comment]
cat XXXXXXXXX  EOF和结尾的EOF是不是也需要。即完整代码是否如下所示：
```
cat > ./migrate_lv.yaml <<- EOF
apiVersion: hwameistor.io/v1alpha1
kind: LocalVolumeMigrate
metadata:
  namespace: hwameistor
  name: <localVolumeMigrateName>
spec:
  sourceNode: <sourceNodeName>
  targetNodesSuggested: 
  - <targetNodesName1>
  - <targetNodesName2>
  volumeName: <volName>
  migrateAllVols: <true/false>
EOF
```
