### ISSUE TITLE
【可观测】可观测模块增加 ElasticSearch 的运维排障手册的文档

### ISSUE THREAD

**Issue by FKAJerry** [DaoCloud/DaoCloud-docs#4380]
需要补充描述 ElasticSearch 数据塞满时的操作手册。

当 ES 内存占满时，可以选择 **扩容** 或者 **删除数据** 来解决：

根据如下的命令查看 ES 节点的资源占比。
```bash
kubectl get pod -n mcamel-system | grep common-es-cluster-masters-es | awk '{print $1}' | xargs -I {} kubectl exec {} -n mcamel-system -c elasticsearch -- df -h | grep /usr/share/elasticsearch/data
```

**扩容** 的操作（诸多方案中的一种）
在主机节点还有资源的情况下，将 PVC 的容量增大。

通过下面的命令获取  es-data-0 节点 的 PVC 配置，请以实际的环境的 PVC 为准。
```bash
kubectl edit -n mcamel-system pvc elasticsearch-data-mcamel-common-es-cluster-masters-es-data-0
```

修改 `spec.resources.requests.storage` 字段（需要使用的存储类sc可以扩容）
```yaml
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 35Gi  # 调整这里
```

**删除数据**的操作

可以通过kibana页面进入，手动 index 删除。
